# https://docs.travis-ci.com/user/languages/perl/
# also: https://github.com/mjgardner/svn-simple-hook/blob/master/.travis.yml for dzil
language: perl
perl:
  - blead
  - dev
  - 5.26
  - 5.24
  - 5.22
  - 5.20
  - 5.18
  - 5.16
  - 5.14
#  stopping builds; is anyone really still using this version?
#  - 5.12
#  - 5.8
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
  allow_failures:
    - perl: 5.26
    - perl: dev
    - perl: blead
    - perl: blead-thr
sudo: false
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
    - PERL_CPANM_OPT="--verbose"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - dzil --version
#  fixes for updating PPI on some versions of perl
  - cpanm  --notest Test::Warnings Test::ClassAPI Test::CPAN::Meta File::Find::Rule::Perl Perl::MinimumVersion
  - cpanm Pod::Coverage::TrustPod Test::Perl::Critic
